version: "3"

services:
  api:
#   image: unreachstudio/onsettools-api
    build: ./api/
    volumes:
      - './api:/usr/src/'
      - './api/package.json:/usr/src/package.json'
      - '/usr/src/node_modules'
    ports:
      - '4001:4000'
    networks:
      - default
    labels:
      traefik.enable: false

  front:
#   image: unreachstudio/onsettools-front
    build: ./front/
    volumes:
      - './front:/usr/src/'
      - './front/package.json:/usr/src/package.json'
      - '/usr/src/node_modules'
    ports:
      - '3001:3000'
    networks:
      - default
    labels:
      traefik.enable: false

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: onset
    volumes:
      - ./db/data:/data/db
    networks:
      - default
    labels:
      traefik.enable: false

  mongo-express:
    image: mongo-express
    ports:
      - '8083:8081'
    networks:
      - default
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: onset
    labels:
      traefik.enable: false

networks:
  default:
# traefik_traefik:
#   external: true
